### ISSUE TITLE
"It looks like you haven't purchased this skill"

### ISSUE THREAD

**Issue by joe2BA** [cakebarIO/QuickAdd-for-Todoist#13]
I'm excited to hopefully get started with this skill. 

The app is enabled and I've linked my account on my android phone. I don't have the todoist app installed on my phone so it should have linked via browser. 

When I follow the instruction to purchase skill by saying "Alexa, open quick add", I receive the response "It looks like you haven't purchased this skill. Sorry, I am unable to fulfill your request on this device........"

Am I missing something?

**Comment by joe2BA** [comment]
Another note - I do have voice purchasing enabled so that anyone can make voice purchases.

**Comment by cakebarIO** [comment]
Hello! Thank you for reaching out. This one is...interesting. Confusing. When you purchased it, did Alexa ask if you wanted to buy and then for your purchasing pin?

You should not be hitting that case response for a response unless you've already purchased.

**Comment by cakebarIO** [comment]
Another question...what device is it saying this on?

**Comment by joe2BA** [comment]
I figured it out. I tried purchasing the skill via my phone which apparently can't be done, so I bought an echo. Works great. Ty

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cakebarIO** [comment]
Perfect! Thank you for reaching out and letting me know!
