### ISSUE TITLE
Erroneous Refund Response

### ISSUE THREAD

**Issue by cakebarIO** [cakebarIO/QuickAdd-for-Todoist#8]
I am still trying to figure this out, but occasionally Alexa may respond to a valid "Add" or "Open" invocation with a "Refund" response. 

Rest assured no refund has happened and you may still use the skill as normal. 

The only way a valid refund can happen is if you Open the skill and specifically request a refund within 3 days of purchasing.

**Comment by ajcherry** [comment]
FYI, I also recently got this response when attempting what I'm pretty sure is an unsupported command ("Alexa, remove potatoes from my shopping list").  I reported the issue from the Alexa app before I checked here and saw this open issue.  Just noting here that it can also happen with invocations other than "open" or "add".

**Comment by cakebarIO** [comment]
Hello! Currently, removing items from a list cannot be done with the skill...and thank you for the triage steps. Yes...I believe this "refund" bug happens when the skill doesn't understand a request. I am in the early stages of developing an all-encompassing solution to fix it.

**Comment by cakebarIO** [comment]
I figured out a fix to this and it is currently in testing. It is kind of a hack, but now, when Alexa doesn't understand a user's request when the skill is open, it should respond with, "Sorry, that was not a clear or valid request. Please say, "Alexa, open Quick Add," or clearly repeat what you just said."
